### ISSUE TITLE
Bot is spamming

### ISSUE THREAD

**Issue by diogotcorreia** [ric2b/votacoes-assembleia-da-republica#3]
@ric2b Bot has been spamming the same posts for the last few days. Probably not saving state.

**Comment by ric2b** [comment]
I disabled it for now, will look into it, thanks for the notice.

**Comment by diogotcorreia** [comment]
```
 Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/votacoes-assembleia-da-republica/votacoes-assembleia-da-republica/votacoes_assembleia_da_republica/update_account.py", line 105, in <module>
    update('XVI')
  File "/home/runner/work/votacoes-assembleia-da-republica/votacoes-assembleia-da-republica/votacoes_assembleia_da_republica/update_account.py", line 100, in update
    m.post_vote(render_vote(new_vote_for_result), reply_to = result_thread, idempotency_key = vote_id)
  File "/home/runner/work/votacoes-assembleia-da-republica/votacoes-assembleia-da-republica/votacoes_assembleia_da_republica/mastodon_client.py", line 25, in post_vote
    return self.client.status_reply(reply_to, rendered_vote, visibility = 'unlisted', idempotency_key = idempotency_key, language = 'pt')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/mastodon/utility.py", line 49, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/mastodon/statuses.py", line 362, in status_reply
    return self.status_post(**keyword_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/mastodon/utility.py", line 49, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/mastodon/statuses.py", line 248, in status_post
    return self.__status_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/mastodon/statuses.py", line 182, in __status_internal
    return self.__api_request('POST', '/api/v1/statuses', params, headers=headers, use_json=use_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/non-package-mode-EVKSkGP_-py3.12/lib/python3.12/site-packages/mastodon/internals.py", line 297, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonAPIError: ('Mastodon API returned error', 422, 'Unprocessable Content', 'Validation failed: Text limite de caracter excedeu 500')
```

Just realized this runs as a GitHub Action. Then the error is this one ^
Seems to be exceeding the maximum post length, so it skips the save state phase in the workflow.

https://github.com/ric2b/votacoes-assembleia-da-republica/actions/runs/11430467375/job/31798075167
